### ISSUE TITLE
Initialize Frontend project

### ISSUE THREAD

**Issue by zzvara** [selenium-monitoring/frontend#1]
- [x] Initialize Angular project with proper [`README.adoc`](https://asciidoc.org/).
- [x] Add [NG-Zorro](https://ng.ant.design/components/popover/en) and adopt its component library.
- [x] Create wireframe. Get motivated by [Enlink](http://preview.themeforest.net/item/enlink-angular-admin-template/full_screen_preview/23804615?_ga=2.169988136.905216233.1697210252-941781739.1692551915).
- [ ] Check and plan how to generate Open API/Swagger API JSON and then generate Angular client code from Go API.

**Comment by levinyiro** [comment]
https://medium.com/sohoffice/the-api-first-strategy-use-swagger-to-generate-api-client-as-an-angular-library-66964ea43587

**Comment by levinyiro** [comment]
https://www.figma.com/file/SJpl9wrSFDsnXQsMIXg1OV/Selenium-monitoring?type=design&node-id=0%3A1&mode=design&t=fdW6I4Ob5AWCMeaw-1
